### ISSUE TITLE
(instance instanceof Seeder) not working - src/utils/commandUtils.ts#L26

### ISSUE THREAD

**Issue by AaronNGray** [jorgebodega/typeorm-seeding#298]
# Example problem demo

https://github.com/AaronNGray/typeorm-seeding-test

# Explanation

https://github.com/jorgebodega/typeorm-seeding/blob/next/src/utils/commandUtils.ts#L26
```
  const seeders: Constructable<Seeder>[] = []
    for (const fileExport in seederFileExports) {
      const seederExport = seederFileExports[fileExport]
      const instance = new seederExport()
      if (instance instanceof Seeder) {
        seeders.push(seederExport)
      }
    }
```
https://github.com/jorgebodega/typeorm-seeding/blob/next/src/seeder.ts
```
import type { DataSource } from 'typeorm'

export abstract class Seeder {
  abstract run(dataSource: DataSource): Promise<void>
}
```
https://github.com/AaronNGray/typeorm-seeding-test/blob/master/src/seeders/CreateUsers.ts
```
import { DataSource } from 'typeorm'
import { Seeder } from '@jorgebodega/typeorm-seeding'
import { User } from '../entity/User'
import { UserFactory } from '../factories/UserFactory';

export default class CreateUsers implements Seeder {
    async run(dataSource: DataSource): Promise<void> {
        const userFactory = new UserFactory();
        const CreatedUsers = await userFactory.makeMany(10);
        const users: User[] = CreatedUsers;
        console.log("users = ", users);
        await dataSource.createEntityManager().save<User>(users);
    }
}
```
```
console.log("Seeder =", Seeder);
console.log("CreateUsers instanceof Seeder =", CreateUsers instanceof Seeder);  // == false
```

The `(instance instanceof Seeder)` will never work !

Example :-

https://gist.github.com/AaronNGray/157f22983f21fb3496a087b1d959c9f3

**Comment by AaronNGray** [comment]
Solved using `extends` rather than `implements`.

```
import { DataSource } from 'typeorm'
import { Seeder } from '@jorgebodega/typeorm-seeding'
import { User } from '../entity/User'
import { UserFactory } from '../factories/UserFactory';

export default class CreateUsers extends Seeder {
    async run(dataSource: DataSource): Promise<void> {
        const userFactory = new UserFactory();
        const CreatedUsers = await userFactory.makeMany(10);
        const users: User[] = CreatedUsers;
        console.log("users = ", users);
        await dataSource.createEntityManager().save<User>(users);
    }
}
```

**Comment by AaronNGray** [comment]
Still getting :-
```
CreateUsers instanceof Seeder = false
```
```
C:\Users\aaron\Test\typeorm-seeding-test-2>npm run seed:run

> typeorm-seeding-test@0.0.1 seed:run
> ts-node ./node_modules/@jorgebodega/typeorm-seeding/dist/cli.js seed -d src/data-source.ts src/seeders/**/*.ts

✔ Datasource loaded
⠋ Importing seedersseederFiles =  [
  'C:/Users/aaron/Test/typeorm-seeding-test-2/src/seeders/CreateUsers.ts'
]
Seeder = [class Seeder]
CreateUsers instanceof Seeder = false
seederFileExports =  [ [Function: CreateUsers] ]
seederExport =  [Function: CreateUsers]
✖ Could not load seeders!
SeederImportationError: Could not load default seeders!
    at Command.run (C:\Users\aaron\Test\typeorm-seeding-test-2\node_modules\@jorgebodega\typeorm-seeding\src\commands\seed.command.ts:41:4)
    at async Command.parseAsync (C:\Users\aaron\Test\typeorm-seeding-test-2\node_modules\commander\lib\command.js:916:5)    at async bootstrap (C:\Users\aaron\Test\typeorm-seeding-test-2\node_modules\@jorgebodega\typeorm-seeding\src\commands\seed.command.ts:72:1) {
  [cause]: TypeError: Class constructor Seeder cannot be invoked without 'new'
      at new CreateUsers (C:\Users\aaron\Test\typeorm-seeding-test-2\src\seeders\CreateUsers.ts:59:42)
      at Function.loadSeeders (C:\Users\aaron\Test\typeorm-seeding-test-2\node_modules\@jorgebodega\typeorm-seeding\src\utils\commandUtils.ts:28:8)
      at async Command.run (C:\Users\aaron\Test\typeorm-seeding-test-2\node_modules\@jorgebodega\typeorm-seeding\src\commands\seed.command.ts:37:13)
      at async Command.parseAsync (C:\Users\aaron\Test\typeorm-seeding-test-2\node_modules\commander\lib\command.js:916:5)
      at async bootstrap (C:\Users\aaron\Test\typeorm-seeding-test-2\node_modules\@jorgebodega\typeorm-seeding\src\commands\seed.command.ts:72:1)
}

C:\Users\aaron\Test\typeorm-seeding-test-2>\utils\sqlite3
```

**Comment by AaronNGray** [comment]
There is no reason this should not work properly. I have done a separate test with a test base class NPM repo and a derived one and its working fine. So I will see if I can work out what is going on here and hopefully create a pull request.

**Comment by AaronNGray** [comment]
Working demo example :- https://github.com/AaronNGray/typeorm-seeding-example
