### ISSUE TITLE
 Could not load seeders!

### ISSUE THREAD

**Issue by jagoanmamah** [jorgebodega/typeorm-seeding#313]
<img width="539" alt="Screenshot 2023-12-26 at 07 55 37" src="https://github.com/jorgebodega/typeorm-seeding/assets/25195185/658d4af0-1e51-451a-9d25-00ed8463d39d">

[
<img width="1160" alt="Screenshot 2023-12-26 at 07 54 19" src="https://github.com/jorgebodega/typeorm-seeding/assets/25195185/d6045214-155e-4d40-96c1-d03f347d227b">
](url)

**Comment by jorgebodega** [comment]
Sorry, I cannot work just with an image without any context.

Please, try to create a reproducible example in a repo, or at least, a decent amount of code.

**Comment by 6uliver** [comment]
I ran into the same issue, I debugged it: the problem is that the "run" method receives the following array as paths: `[ 'seed', './seed/0_clear.ts', './seed/1_create_users.ts', ... ]`

@jagoanmamah did you have a seed folder too? Based on the image your case can be a different one.

The root cause is that the seed command is prepended to the paths array (maybe the "commander" package is misused) and if you store the seeds under a folder named "seed" you can see this error message because we try to load the module from that folder.

I figured out two workarounds, both of them are working independently:
1. Remove the "seed" command when calling the CLI (for me it's something like that: `ts-node -r tsconfig-paths/register ./node_modules/@jorgebodega/typeorm-seeding/dist/cli.js -d ./data-source.ts ./seed/*.ts`)
2. Rename the "seed" folder to something else, for example "seeders": (for me it's something like that: `ts-node -r tsconfig-paths/register ./node_modules/@jorgebodega/typeorm-seeding/dist/cli.js seed -d ./data-source.ts ./seeders/*.ts`)

I don't have time to fix this issue and send a PR but I hope these informations are going to help you!

**Comment by daviddivinefavour** [comment]
// create-admin.seed.ts
```ts
import { DataSource } from 'typeorm';
import * as bcrypt from 'bcrypt';
import { Admin } from 'src/modules/admin/entities/admin.entity';
import { EAdminRole } from 'src/modules/admin/types/admin.types';
import { Seeder } from '@jorgebodega/typeorm-seeding';

export default class AdminSeeder extends Seeder {
  async run(dataSource: DataSource) {
    console.log('Seeding admin\n\n\n');
    // Hash the password
    const saltRounds = 10;
    const hashedPassword = await bcrypt.hash('password', saltRounds);

    // Create new admin
    const admin = new Admin();
    admin.firstName = 'Admin';
    admin.lastName = 'User';
    admin.email = 'admin@example.com';
    admin.phoneNumber = '+234700000000';
    admin.hashedPassword = hashedPassword;
    admin.role = EAdminRole.SUPER_ADMIN;

    await dataSource.createEntityManager().save<Admin>([admin]);
  }
}

```
following the first workaround @6uliver mentioned, I was finally able to go past the initial error 

```bash
yarn seed:run
yarn run v1.22.22
$ typeorm-seeding seed -d src/database/data-source.js  src/database/seeders/*.ts
✔ Datasource loaded
✖ Could not load seeders!
/Users/divinefavourdavid/projects/waitlist/api-service/node_modules/@jorgebodega/typeorm-seeding/dist/commands/seed.command.js:37
        throw new errors_1.SeederImportationError("Could not load default seeders!", {
              ^

SeederImportationError: Could not load default seeders!
    at Command.run (<>/node_modules/@jorgebodega/typeorm-seeding/dist/commands/seed.command.js:37:15)
    at async Command.parseAsync (<>/node_modules/@jorgebodega/typeorm-seeding/node_modules/commander/lib/command.js:1092:5)
    at async bootstrap (<>/node_modules/@jorgebodega/typeorm-seeding/dist/commands/seed.command.js:66:5) {
  [cause]:<>/src/database/seeders/create-admin.seed.ts:1
  import { DataSource } from 'typeorm';
  ^^^^^^
  
  SyntaxError: Cannot use import statement outside a module
      at internalCompileFunction (node:internal/vm:76:18)
      at wrapSafe (node:internal/modules/cjs/loader:1283:20)
      at Module._compile (node:internal/modules/cjs/loader:1328:27)
      at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)
      at Module.load (node:internal/modules/cjs/loader:1203:32)
      at Module._load (node:internal/modules/cjs/loader:1019:12)
      at Module.require (node:internal/modules/cjs/loader:1231:19)
      at require (node:internal/modules/helpers:177:18)
      at tryToRequire (<>/node_modules/typeorm/util/ImportUtils.js:20:17)
      at importOrRequireFile (<>/node_modules/typeorm/util/ImportUtils.js:34:24)
}
```

But I came across a different error:
```sh
yarn seed:run
yarn run v1.22.22
$ ts-node -r tsconfig-paths/register ./node_modules/@jorgebodega/typeorm-seeding/dist/cli.js -d src/database/data-source.js  src/database/seeders/*.ts
✔ Datasource loaded
✔ Seeder imported
ℹ Executing seeders...
⠋ Executing AdminSeederSeeding admin



✖ Could not execute seeder!
SeederExecutionError: Could not execute seeder!
    at Command.run (<>/node_modules/@jorgebodega/typeorm-seeding/src/commands/seed.command.ts:57:9)
    at async Command.parseAsync (<>/node_modules/@jorgebodega/typeorm-seeding/node_modules/commander/lib/command.js:1092:5)
    at async bootstrap (<>/node_modules/@jorgebodega/typeorm-seeding/src/commands/seed.command.ts:77:2) {
  [cause]: EntityMetadataNotFoundError: No metadata for "Admin" was found.
      at DataSource.getMetadata (<>/node_modules/src/data-source/DataSource.ts:450:30)
      at <>/node_modules/src/persistence/EntityPersistExecutor.ts:85:30
      at Array.forEach (<anonymous>)
      at <>/node_modules/src/persistence/EntityPersistExecutor.ts:77:30
      at Array.map (<anonymous>)
      at EntityPersistExecutor.execute (<>/node_modules/src/persistence/EntityPersistExecutor.ts:73:34)
      at async AdminSeeder.run (<>/src/database/seeders/create-admin.seed.ts:23:5)
      at async useSeeders (<>/node_modules/@jorgebodega/typeorm-seeding/src/helpers/useSeeders.ts:10:3)
      at async Command.run (<>/node_modules/@jorgebodega/typeorm-seeding/src/commands/seed.command.ts:51:4)
      at async Command.parseAsync (<>/node_modules/@jorgebodega/typeorm-seeding/node_modules/commander/lib/command.js:1092:5)
}
```

Any idea where the metadata mentioned in the error should be defined?

**Comment by alumni** [comment]
The actual reason why this usually fails is in the user code, which should be referenced in the error cause, but for some reason, the error cause it not printed for me:

```
[2026-02-22T22:27:17.608Z] ERROR    Error: Could not execute seeder!
    at Command.run (.../node_modules/@jorgebodega/typeorm-seeding/src/commands/seed.command.ts:57:9)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async Command.parseAsync (.../node_modules/commander/lib/command.js:1092:5)
    at async bootstrap (.../@jorgebodega/typeorm-seeding/src/commands/seed.command.ts:77:2)
```
